"""Add_reservation_model

Revision ID: 305df3680d4e
Revises: 
Create Date: 2025-03-31 17:47:47.230683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '305df3680d4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_project', schema=None) as batch_op:
        batch_op.drop_index('idx_businessLineId')
        batch_op.drop_index('idx_gitName')

    op.drop_table('tb_project')
    with op.batch_alter_table('tb_test_model', schema=None) as batch_op:
        batch_op.drop_index('alias')

    op.drop_table('tb_test_model')
    with op.batch_alter_table('tb_interface_cover_info', schema=None) as batch_op:
        batch_op.drop_index('PROJECT_ID_INDEX')
        batch_op.drop_index('STATE_INDEX')

    op.drop_table('tb_interface_cover_info')
    with op.batch_alter_table('tb_business_line', schema=None) as batch_op:
        batch_op.drop_index('bussinessLineName')

    op.drop_table('tb_business_line')
    with op.batch_alter_table('api_param_detail', schema=None) as batch_op:
        batch_op.drop_index('index_interface_id')

    op.drop_table('api_param_detail')
    op.drop_table('tb_pipeline_board')
    with op.batch_alter_table('test_demo', schema=None) as batch_op:
        batch_op.drop_index('alias')

    op.drop_table('test_demo')
    op.drop_table('tb_notify_qywx_history')
    op.drop_table('chart_config')
    op.drop_table('tb_regular_check')
    op.drop_table('tb_codediff_module')
    op.drop_table('tb_task_list')
    op.drop_table('checklistinfo')
    op.drop_table('tb_email_config')
    with op.batch_alter_table('api_strategy_detail', schema=None) as batch_op:
        batch_op.drop_index('index_strategy_no')

    op.drop_table('api_strategy_detail')
    op.drop_table('tb_pipeline_configure_dayu')
    op.drop_table('tb_project_run')
    op.drop_table('tb_stability_pro')
    op.drop_table('api_change')
    op.drop_table('tb_auto_task_data')
    op.drop_table('tb_user')
    op.drop_table('tb_check_online')
    with op.batch_alter_table('tb_interface_cover_info_bak', schema=None) as batch_op:
        batch_op.drop_index('PROJECT_ID_INDEX')
        batch_op.drop_index('STATE_INDEX')

    op.drop_table('tb_interface_cover_info_bak')
    op.drop_table('tb_task_config')
    with op.batch_alter_table('tb_config', schema=None) as batch_op:
        batch_op.drop_index('basecode')

    op.drop_table('tb_config')
    op.drop_table('tb_requirement_cover_detail')
    with op.batch_alter_table('tb_demo', schema=None) as batch_op:
        batch_op.drop_index('alias')

    op.drop_table('tb_demo')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('auth_group')
    op.drop_table('api_source')
    op.drop_table('tb_task_case')
    op.drop_table('tb_check_online_config')
    op.drop_table('tb_case_count')
    op.drop_table('tb_cover_detail')
    with op.batch_alter_table('tb_add_cron', schema=None) as batch_op:
        batch_op.drop_index('ix_tb_add_cron_next_run_time')

    op.drop_table('tb_add_cron')
    op.drop_table('tb_autoinfo_staff')
    op.drop_table('case_auto_status')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index('django_session_expire_date_a5c62663')

    op.drop_table('django_session')
    with op.batch_alter_table('tb_pipeline_configure', schema=None) as batch_op:
        batch_op.drop_index('idx_statistic_task_id')

    op.drop_table('tb_pipeline_configure')
    op.drop_table('tb_jenkins_job')
    op.drop_table('tb_jenkins_jacoco')
    op.drop_table('tb_inspect')
    with op.batch_alter_table('tb_interface_sum', schema=None) as batch_op:
        batch_op.drop_index('idx_project_id')

    op.drop_table('tb_interface_sum')
    op.drop_table('strategy_path_relation')
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq')

    op.drop_table('django_content_type')
    op.drop_table('tb_case_show_info')
    op.drop_table('tb_codediff_config')
    op.drop_table('tb_notify_qywx')
    op.drop_table('tb_staff_week_report')
    op.drop_table('tb_target')
    op.drop_table('tb_autoinfo_project')
    with op.batch_alter_table('tb_statistic_task_execute_info', schema=None) as batch_op:
        batch_op.drop_index('PROJECT_ID_INDEX')
        batch_op.drop_index('STATE_INDEX')
        batch_op.drop_index('idx_projectId_addTime')

    op.drop_table('tb_statistic_task_execute_info')
    with op.batch_alter_table('api_info', schema=None) as batch_op:
        batch_op.drop_index('index_domain_online')
        batch_op.drop_index('index_path')

    op.drop_table('api_info')
    op.drop_table('tb_cron_show')
    op.drop_table('tb_dayu_jacoco')
    op.drop_table('tb_search_lbt')
    op.drop_table('tb_code_diff')
    op.drop_table('tb_soso_case')
    op.drop_table('django_migrations')
    op.drop_table('tb_autoflow_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_autoflow_request',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('env_name', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('module_name', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('request_id', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('branch', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('git', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('msg', mysql.VARCHAR(length=512), server_default=sa.text("''"), nullable=False),
    sa.Column('needcallback', mysql.VARCHAR(length=1), server_default=sa.text("''"), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('iscallback', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('update_time', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_soso_case',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('case_desc', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('business_direction_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('business_line_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('system_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sub_system_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('business_direction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('business_line_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('system_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sub_system_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('uri', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('headers', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('body_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('body_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('params', mysql.VARCHAR(length=4000), nullable=True),
    sa.Column('vars_pre', mysql.LONGTEXT(), nullable=True),
    sa.Column('vars_post', mysql.LONGTEXT(), nullable=True),
    sa.Column('sourceId_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_code_diff',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gitKey', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('branch', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('link_url', mysql.LONGTEXT(), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('compareUrl', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_search_lbt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('path', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('pathJson', mysql.LONGTEXT(), nullable=True),
    sa.Column('pathCaseAmount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('caseCreate', mysql.LONGTEXT(), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_dayu_jacoco',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('git_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('download_url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('env_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('branch_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('commit_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_cron_show',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cron_id', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('taskName', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('cronTime', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('notifyId', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('interface', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('user_group', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('cronType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('header', mysql.LONGTEXT(), nullable=True),
    sa.Column('param', mysql.LONGTEXT(), nullable=True),
    sa.Column('postJson', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('api_info',
    sa.Column('id', mysql.INTEGER(display_width=8), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('bdid', mysql.INTEGER(display_width=8), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务方向id'),
    sa.Column('bdname', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='业务方向名称'),
    sa.Column('blid', mysql.INTEGER(display_width=8), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务线id'),
    sa.Column('blname', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='业务线名称'),
    sa.Column('sysid', mysql.INTEGER(display_width=8), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='系统id'),
    sa.Column('sysname', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='系统名称'),
    sa.Column('subsysid', mysql.INTEGER(display_width=8), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='子系统id'),
    sa.Column('subsysname', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='子系统名称'),
    sa.Column('git_url', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='git地址'),
    sa.Column('peiqiproid', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='佩奇项目id'),
    sa.Column('path', mysql.VARCHAR(length=170), server_default=sa.text("''"), nullable=False, comment='接口地址'),
    sa.Column('interfacedesc', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='接口描述'),
    sa.Column('sososervicename', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='soso服务名称'),
    sa.Column('domain_online', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='线上域名'),
    sa.Column('dubboname', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=False, comment='dubbo类名称'),
    sa.Column('dubbomethod', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='dubbo方法名称'),
    sa.Column('code_format', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False, comment='dubbo编码方式'),
    sa.Column('header', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='header'),
    sa.Column('method', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('requestType', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False, comment='请求类型 http ,dubbo'),
    sa.Column('params', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='请求参数'),
    sa.Column('params_online', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='请求参数值-diff线上'),
    sa.Column('body', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='请求体'),
    sa.Column('body_online', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='请求体-diff线上'),
    sa.Column('body_type', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='body格式'),
    sa.Column('return_content', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='返回体'),
    sa.Column('return_online', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='返回值-diff线上'),
    sa.Column('prescript', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='数据准备'),
    sa.Column('make_again', mysql.VARCHAR(length=3), server_default=sa.text("''"), nullable=False, comment='重新溯源1-落兵台，2-线上日志，3-soso，4-ketrace'),
    sa.Column('strategy_no', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='生成策略'),
    sa.Column('strategy_todo', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='未完成的策略'),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('create_pr', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=False, comment='创建人'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('update_pr', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=False, comment='更新人'),
    sa.Column('other2', mysql.VARCHAR(length=8), server_default=sa.text("'1'"), nullable=False, comment='备用2'),
    sa.Column('status', mysql.VARCHAR(length=2), server_default=sa.text("'1'"), nullable=False, comment='状态 1-有效 0-无效'),
    sa.Column('need_attachment', mysql.INTEGER(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='dubbo-隐式传参，0-不需要，1-需要'),
    sa.Column('attachment', mysql.VARCHAR(length=2048), server_default=sa.text("'0'"), nullable=False, comment='dubbo隐式传参的attachment'),
    sa.PrimaryKeyConstraint('id'),
    comment='标准接口信息表',
    mysql_comment='标准接口信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('api_info', schema=None) as batch_op:
        batch_op.create_index('index_path', ['path', 'peiqiproid'], unique=False)
        batch_op.create_index('index_domain_online', ['domain_online'], unique=False)

    op.create_table('tb_statistic_task_execute_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('businessLineId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('executeDetailText', mysql.LONGTEXT(), nullable=True),
    sa.Column('testResult', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('codeCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('methonCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('branchCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('executeStartTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('executeTaketime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('httpConfKey', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('executeType', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('executeBy', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pipelineName', mysql.VARCHAR(length=400), server_default=sa.text("''"), nullable=False, comment='keones的pipeline_name'),
    sa.Column('comments', mysql.VARCHAR(length=4000), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=4000), nullable=False),
    sa.Column('casetype', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('commitSha', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('branchName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('modBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('oldExecId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('commitId', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('buildNum', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('jobName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('reasonType', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('testReportUrl', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('sosoTasks', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='soso任务'),
    sa.Column('addCoverUrl', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('codeAddCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('countAddCover', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notCover', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('line_sum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('interfaceCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('interfaceCoverageToday', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=False, comment='当天的接口覆盖率'),
    sa.Column('interfaceTodayCoverNum', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='当天当前的总接口覆盖数'),
    sa.Column('interfaceAllNum', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='总接口数'),
    sa.Column('caseAllNum', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='近30天上报过的任务/任务集里soso包含的接口数'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_statistic_task_execute_info', schema=None) as batch_op:
        batch_op.create_index('idx_projectId_addTime', ['projectId', 'addTime'], unique=False)
        batch_op.create_index('STATE_INDEX', ['state'], unique=False)
        batch_op.create_index('PROJECT_ID_INDEX', ['projectId'], unique=False)

    op.create_table('tb_autoinfo_project',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('interface_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('all_interfaces_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_interfaces_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_interfaces_desc', mysql.LONGTEXT(), nullable=True),
    sa.Column('start_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('end_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('business_line', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('extend_field', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_target',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('casetype', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('target_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('target_value', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('target_value_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('finish_date', sa.DATE(), nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('effect_date', sa.DATE(), nullable=True),
    sa.Column('satisfied_date', sa.DATE(), nullable=True),
    sa.Column('whether_effect', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('whether_satisfied', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_staff_week_report',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('all_interface_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('all_dubbo_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('all_http_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_dubbo_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_http_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_interface_desc', mysql.LONGTEXT(), nullable=True),
    sa.Column('business_line', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('start_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('end_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('extend_field', mysql.LONGTEXT(), nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_notify_qywx',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notify_reason', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('user_group', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('notify_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('notify_template', mysql.LONGTEXT(), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('app_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message_token', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_codediff_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('module', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gitKey', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('gitUrl', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('profile', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('admin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_case_show_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('caseCode', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('interface', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('taskId', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', ['app_label', 'model'], unique=False)

    op.create_table('strategy_path_relation',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('path', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=False),
    sa.Column('strategy_nos', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=False),
    sa.Column('operator', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('add_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_interface_sum',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('business_line_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('interface_sum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_interface_sum', schema=None) as batch_op:
        batch_op.create_index('idx_project_id', ['project_id'], unique=False)

    op.create_table('tb_inspect',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('business_direction', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('business_line', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('system', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('sub_system', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('test_env', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('task_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_jenkins_jacoco',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='项目id'),
    sa.Column('project_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='项目名'),
    sa.Column('git_address', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='项目git地址ssh形式'),
    sa.Column('job_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='jenkins Job节点名'),
    sa.Column('branch_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='分支名称'),
    sa.Column('build_id', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='构建id'),
    sa.Column('commit_id', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='代码提交版本号'),
    sa.Column('branch_name_build_id', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='分支及Jenkins构建id'),
    sa.Column('jacoco_conf', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='服务ip:port的配置'),
    sa.Column('type', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='非大禹的数据来源类型，jenkins，阿基米德'),
    sa.Column('creator', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='项目责任用户'),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_jenkins_job',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('job_name', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('off_on', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('ci_server', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_pipeline_configure',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('jenkins_job_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('jenkins_job_name_online', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('soso_task_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('statistic_task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('alive_check', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('eva_env', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('eva_ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('code_cover_model', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('business_line_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('business_line', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('test_env_ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('test_env_ip_port', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('smoke_switch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('smoke_task_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dayu_server', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dayu_soso_task_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('auto_plat', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_pipeline_configure', schema=None) as batch_op:
        batch_op.create_index('idx_statistic_task_id', ['statistic_task_id'], unique=False)

    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index('django_session_expire_date_a5c62663', ['expire_date'], unique=False)

    op.create_table('case_auto_status',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('related_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=3), autoincrement=False, nullable=True),
    sa.Column('message', mysql.VARCHAR(length=2000), server_default=sa.text("''"), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('ucid', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=False),
    sa.Column('path', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='接口'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_autoinfo_staff',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('interface_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('all_interfaces_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_interfaces_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_interfaces_desc', mysql.LONGTEXT(), nullable=True),
    sa.Column('start_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('end_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('business_line', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('extend_field', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_add_cron',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_add_cron', schema=None) as batch_op:
        batch_op.create_index('ix_tb_add_cron_next_run_time', ['next_run_time'], unique=False)

    op.create_table('tb_cover_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jenkins_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('commit_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('add_cover', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('add_branch_cover', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('all_cover', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('all_branch_cover', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('add_report_url', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('all_report_url', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('creator', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('businessline_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('test_result', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('modBy', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('branch_name_build_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('branch_name', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='分支名称'),
    sa.Column('build_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='构建号'),
    sa.Column('jacoco_conf', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bdId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务方向id'),
    sa.Column('blId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务组id'),
    sa.Column('sysId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务线id'),
    sa.Column('subsysId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务id'),
    sa.Column('bdId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务方向name'),
    sa.Column('blId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务组name'),
    sa.Column('sysId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务线name'),
    sa.Column('subsysId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务name'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_case_count',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('auto_task', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('case_creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('case_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('extend_field', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_check_online_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('config_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('config_value', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('admin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('admin_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_task_case',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('source', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('case_ids', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('pass_rate', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('task_report', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('case_abandon', mysql.VARCHAR(length=5000), server_default=sa.text("''"), nullable=False, comment='case标记不在加回'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('api_source',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('interface_id', mysql.INTEGER(display_width=9), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='接口id'),
    sa.Column('peiqiproid', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='佩琦项目id'),
    sa.Column('git_url', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='git地址'),
    sa.Column('path', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='接口路径'),
    sa.Column('lbt_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='落兵台源头信息'),
    sa.Column('diff_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='diff源头信息'),
    sa.Column('soso_source', mysql.VARCHAR(length=4096), server_default=sa.text("''"), nullable=False, comment='soso源头信息'),
    sa.Column('ketrace_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='ketrace源头信息'),
    sa.Column('total_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='汇总源头信息'),
    sa.Column('creat_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('create_pre', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='创建者'),
    sa.Column('update_pre', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='更新者'),
    sa.Column('status', mysql.VARCHAR(length=3), server_default=sa.text("'1'"), nullable=False, comment='状态1有效0无效'),
    sa.Column('swagger_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='swager源头信息'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('tb_demo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('modBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_demo', schema=None) as batch_op:
        batch_op.create_index('alias', ['alias'], unique=False)

    op.create_table('tb_requirement_cover_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='项目id'),
    sa.Column('requirement_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='keones需求id'),
    sa.Column('requirement_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='keones需求标题name'),
    sa.Column('execute_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='流水线id'),
    sa.Column('git_address', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='git地址'),
    sa.Column('env_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='大禹环境名称'),
    sa.Column('branch_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='分支名称'),
    sa.Column('commit_id', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='代码版本号'),
    sa.Column('add_cover', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=True, comment='增量代码覆盖率'),
    sa.Column('all_cover', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=True, comment='全量代码覆盖率'),
    sa.Column('add_report_url', mysql.VARCHAR(length=2555), server_default=sa.text("''"), nullable=True, comment='增量代码覆盖率报告'),
    sa.Column('all_report_url', mysql.VARCHAR(length=2555), server_default=sa.text("''"), nullable=True, comment='全量代码覆盖率报告'),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='0：进行中，1：成功，2：失败'),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=True, comment='更新时间'),
    sa.Column('exec_user', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='执行人'),
    sa.Column('relation_git_list', mysql.VARCHAR(length=2000), server_default=sa.text("''"), nullable=True, comment='需求相关git地址列表信息'),
    sa.Column('relation_users', mysql.VARCHAR(length=555), server_default=sa.text("''"), nullable=False, comment='需求相关人'),
    sa.Column('callback_url', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='回调url'),
    sa.Column('step', mysql.INTEGER(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='触发阶段，1：提测，2：测试完成，0：其他'),
    sa.Column('threshold_sc', mysql.INTEGER(display_width=3), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='提测阶段增量覆盖率阈值，pipeline中设置'),
    sa.Column('threshold_cw', mysql.INTEGER(display_width=3), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='测试完成阶段增量覆盖率阈值，pipeline中设置'),
    sa.Column('reason', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='覆盖率计算失败的原因'),
    sa.Column('bdId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务方向id'),
    sa.Column('blId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务组id'),
    sa.Column('sysId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务线id'),
    sa.Column('subsysId', mysql.INTEGER(display_width=10), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='业务id'),
    sa.Column('bdId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务方向name'),
    sa.Column('blId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务组name'),
    sa.Column('sysId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务线name'),
    sa.Column('subsysId_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='业务name'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('basecode', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('codevalue', mysql.VARCHAR(length=10000), nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_config', schema=None) as batch_op:
        batch_op.create_index('basecode', ['basecode'], unique=False)

    op.create_table('tb_task_config',
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_group', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('template', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('notify', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('classify', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('source_update', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_interface_cover_info_bak',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('businessLineId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('interface', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('frequency', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isInput', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('isPossible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('isFullCovered', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('creatTime', mysql.DATETIME(fsp=6), server_default=sa.text("'1970-01-01 01:01:01.000000'"), nullable=False),
    sa.Column('isCore', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_interface_cover_info_bak', schema=None) as batch_op:
        batch_op.create_index('STATE_INDEX', ['state'], unique=False)
        batch_op.create_index('PROJECT_ID_INDEX', ['projectId'], unique=False)

    op.create_table('tb_check_online',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('check_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('bug_details', mysql.LONGTEXT(), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('check_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('case_details', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('keones_online_bug_url', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ucid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('usercode', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_auto_task_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('proDetail', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('businessLineId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('systemType', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gitName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dutyPerson', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('casetype', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('codeCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('codeCovRaise', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('methodCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('methodCovRaise', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('branchCoverage', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('branchCovRaise', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('passTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('passRate', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('passRateRaise', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('executeType', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('startTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('endTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('interzone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('zoneType', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=4000), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('createTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('businessLineName', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('caseCount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('caseCountRaise', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('api_change',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('interface_id', mysql.INTEGER(display_width=9), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='接口id'),
    sa.Column('path', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='接口路径'),
    sa.Column('git_url', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='git地址'),
    sa.Column('peiqiproid', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='佩琦项目id'),
    sa.Column('last_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='上一次source信息'),
    sa.Column('new_source', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='最新source信息'),
    sa.Column('diff_detail', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='变更明细节'),
    sa.Column('message_notice', mysql.VARCHAR(length=2), server_default=sa.text("''"), nullable=False, comment='1待通知0已通知'),
    sa.Column('status', mysql.VARCHAR(length=2), server_default=sa.text("''"), nullable=False, comment='1有效，0无效'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_stability_pro',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify_user', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('notify_group', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('stability_day_online', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stability_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('case_fail_online', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('case_fail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_auto_del', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_online', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('env', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_everyday', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('week_day', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('timing', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('taskid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pass_rate', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('stability', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('qw_key', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='线上巡检通知机器人key'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_project_run',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('business_line', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('all_project_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('run_project_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('not_run_project_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('not_run_reason', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('extend_field', mysql.LONGTEXT(), nullable=True),
    sa.Column('user_duty', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_groups', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('user_ids', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('not_run_time', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('project_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('not_run_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_pipeline_configure_dayu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('git_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('code_cover_model', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('alive_check', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('duty_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('soso_task_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('api_strategy_detail',
    sa.Column('id', mysql.INTEGER(display_width=4), autoincrement=True, nullable=False, comment='序号'),
    sa.Column('strategy_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='策略名称'),
    sa.Column('strategy_no', mysql.VARCHAR(length=3), server_default=sa.text("''"), nullable=False, comment='策略标识'),
    sa.Column('strategy_supple', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='策略一级补充'),
    sa.Column('strategy_secsupple', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='策略二级补充'),
    sa.Column('strategy_default', mysql.INTEGER(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='默认策略0-非默认，1-默认'),
    sa.Column('strategy_sort', mysql.INTEGER(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='策略排序id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('api_strategy_detail', schema=None) as batch_op:
        batch_op.create_index('index_strategy_no', ['strategy_no'], unique=False)

    op.create_table('tb_email_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email_user', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('email_group', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('template_type', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('checklistinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('checklistItem', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='项目checklist的验证项'),
    sa.Column('checklistItemType', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='项目checklist验证项结果类型'),
    sa.Column('checklistItemValue', mysql.TEXT(), nullable=True, comment='项目checklist验证项结果值'),
    sa.Column('createTime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('exestep', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='在什么环节校验，1：测试环节，默认1 ; 2:上线环节'),
    sa.Column('roleType', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='校验所属的角色类型，1：qa，默认'),
    sa.Column('state', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='校验项状态，1-用户自定义，2-系统添加'),
    sa.Column('extinfo', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='扩展字段'),
    sa.Column('bdId', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='项目一级层级id'),
    sa.Column('bdName', mysql.VARCHAR(length=50), server_default=sa.text("'二手'"), nullable=False, comment='项目一级层级name'),
    sa.Column('blId', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='项目二级层级id'),
    sa.Column('blName', mysql.VARCHAR(length=50), server_default=sa.text("'二手B端'"), nullable=False, comment='项目二级层级name'),
    sa.Column('sysId', mysql.INTEGER(display_width=11), server_default=sa.text("'3'"), autoincrement=False, nullable=False, comment='项目三级层级id'),
    sa.Column('sysName', mysql.VARCHAR(length=50), server_default=sa.text("'运营平台'"), nullable=False, comment='项目三级层级name'),
    sa.Column('subSysId', mysql.INTEGER(display_width=11), server_default=sa.text("'292'"), autoincrement=False, nullable=False, comment='项目四级层级id'),
    sa.Column('subSysName', mysql.VARCHAR(length=50), server_default=sa.text("'贝壳分'"), nullable=False, comment='项目四级层级name'),
    sa.Column('createUserUcid', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='创建人ucid'),
    sa.Column('keonesUrl', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='keonesUrl地址'),
    sa.Column('directStart', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='立即启用'),
    sa.Column('CheckListWiki', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='CheckListWiki地址'),
    sa.Column('onlinePlan', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='onlinePlan地址'),
    sa.Column('itemsConfData', mysql.TEXT(), nullable=True, comment='checklist配置项'),
    sa.Column('operator', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='操作系统号'),
    sa.Column('requireDesc', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='需求名描述'),
    sa.Column('itemsConftype', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='配置类型1234'),
    sa.Column('checkMode', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='项目纬度，需求纬度'),
    sa.Column('itemsTypeText', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('itemsDataText', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_task_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('start', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('end', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('process', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('confirmer', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timeout', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('classify', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('images', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('operation', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('group', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('source_task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_codediff_module',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('config_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('config_value', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('admin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('admin_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_regular_check',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='项目id'),
    sa.Column('task_type', mysql.VARCHAR(length=10), nullable=False, comment='任务类型，巡检=patrol'),
    sa.Column('task_id', mysql.VARCHAR(length=40), nullable=False, comment='soso任务id'),
    sa.Column('soso_env', mysql.VARCHAR(length=20), nullable=False, comment='soso环境名称'),
    sa.Column('result', mysql.VARCHAR(length=10), nullable=False, comment='执行结果'),
    sa.Column('report', mysql.VARCHAR(length=400), nullable=False, comment='执行报告url'),
    sa.Column('exec_time', mysql.DATETIME(fsp=6), nullable=False, comment='执行时间'),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False, comment='执行人'),
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False, comment='执行人系统号'),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='数据状态 0:无效1:有效'),
    sa.Column('reason', mysql.VARCHAR(length=100), nullable=True, comment='失败原因'),
    sa.Column('reason_type', mysql.VARCHAR(length=10), nullable=True, comment='失败原因类型'),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=200), nullable=True, comment='备注'),
    sa.Column('case_sum', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='case总数'),
    sa.Column('case_pass', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='case执行成功数'),
    sa.Column('update_by', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='失败信息修改人'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('chart_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url_path', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('chart_key', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('value', mysql.LONGTEXT(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_notify_qywx_history',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('notify_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notify_reason', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('user_group', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('notify_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('notify_template', mysql.LONGTEXT(), nullable=True),
    sa.Column('notify_params', mysql.LONGTEXT(), nullable=True),
    sa.Column('notify_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('notify_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('notify_ip', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('notify_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('notify_response', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('notify_result', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test_demo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('modBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('test_demo', schema=None) as batch_op:
        batch_op.create_index('alias', ['alias'], unique=False)

    op.create_table('tb_pipeline_board',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('business_direction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('business_direction_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('business_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('business_group_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('business_line_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('business_line_name', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('qw_msg_member', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('qw_msg_group', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('api_param_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='id'),
    sa.Column('interface_id', mysql.INTEGER(display_width=9), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='接口id'),
    sa.Column('param_key', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=False, comment='参数名字'),
    sa.Column('param_value', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='参数值'),
    sa.Column('param_type', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=False, comment='参数类型'),
    sa.Column('param_isnull', mysql.VARCHAR(length=2), server_default=sa.text("''"), nullable=False, comment='是否必填'),
    sa.Column('param_border', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='边界'),
    sa.Column('status', mysql.VARCHAR(length=2), server_default=sa.text("'1'"), nullable=False, comment='1有效0无效'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('param_enum', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='参数value枚举'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('api_param_detail', schema=None) as batch_op:
        batch_op.create_index('index_interface_id', ['interface_id'], unique=False)

    op.create_table('tb_business_line',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bussinessLineName', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('bussinessLineDesc', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addBy', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modBy', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('sysId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bdId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bdName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('blId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('blName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('sysName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('qwgroup', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('qwusers', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_business_line', schema=None) as batch_op:
        batch_op.create_index('bussinessLineName', ['bussinessLineName'], unique=False)

    op.create_table('tb_interface_cover_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('businessLineId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('interface', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('frequency', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isInput', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updateTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('isPossible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('isFullCovered', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('creatTime', mysql.DATETIME(fsp=6), server_default=sa.text("'1970-01-01 01:01:01.000000'"), nullable=False),
    sa.Column('isCore', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_interface_cover_info', schema=None) as batch_op:
        batch_op.create_index('STATE_INDEX', ['state'], unique=False)
        batch_op.create_index('PROJECT_ID_INDEX', ['projectId'], unique=False)

    op.create_table('tb_test_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('modBy', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_test_model', schema=None) as batch_op:
        batch_op.create_index('alias', ['alias'], unique=False)

    op.create_table('tb_project',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('businessLineId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('systemType', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('proDetail', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('gitName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gitAddres', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('creator', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('addTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('oldtaskid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('oldtitle', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dutyPerson', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('modTime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('qwgroup', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('qwusers', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('update_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('daily', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('access', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('appName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bdId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bdName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('blId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('blName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('moduleName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('subSysId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subSysName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('sysId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sysName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('dubbomoduleName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('autocase', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('alertPlatform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('autoPlatform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('languageType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lbtProId', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('gitMembers', mysql.LONGTEXT(), nullable=True),
    sa.Column('dayu_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notifyPass', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('free_point', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('invalidDays', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='连续N天无流量接口自动无效'),
    sa.Column('whiteRule', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='接口白名单的正则匹配'),
    sa.Column('filterRule', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='接口过滤的正则匹配'),
    sa.Column('domain_test', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('automation_flag', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('case_flag', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Interface_flag', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('swagger_url', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='swagger地址'),
    sa.Column('fixed_header', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='固定header'),
    sa.Column('head_func_key', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='soso关键字'),
    sa.Column('get_header_type', mysql.VARCHAR(length=2), server_default=sa.text("'0'"), nullable=False, comment='0:无规则1:固定header2.动态header'),
    sa.Column('post_header_type', mysql.VARCHAR(length=2), server_default=sa.text("'0'"), nullable=False, comment='0:无规则1:固定header2.动态header'),
    sa.Column('strategy_no', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='case生成策略'),
    sa.Column('auto_finished', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='case自动化是否完成'),
    sa.Column('login_account', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False, comment='登录帐号'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_project', schema=None) as batch_op:
        batch_op.create_index('idx_gitName', ['gitName'], unique=False)
        batch_op.create_index('idx_businessLineId', ['businessLineId'], unique=False)

    op.drop_table('reservations')
    # ### end Alembic commands ###
